databases:
  - name: pwa
    databaseName: pwa
    user: pwa

services:
  - type: web
    name: pwa
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pwa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
